"""Validation QA: compare sampled windows of src vs dst for new artifacts.

Design: full-file DSP on 9hr books is too slow for batch QA, so we decode up
to 3 sampled windows (start/middle/end) whose total length scales with the
user's 1-100% slider but is capped (3-45s each) to keep batch throughput sane.
Thresholds: centroid_shift >8% -> tinny WARN (>25% FAIL); hf_energy +3dB ->
hiss WARN (+6dB FAIL); added transients -> clicks WARN; RMS collapse/silence
or duration mismatch -> FAIL. Returns PASS/WARN/FAIL + metrics + reason.
"""
from __future__ import annotations
import os
import shutil
import subprocess
import tempfile

SR = 22050
MIN_WIN = 3.0
MAX_WIN = 45.0
FRACTIONS = (0.02, 0.48, 0.90)


def _duration(path: str) -> float:
    try:
        r = subprocess.run(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                            "-of", "default=noprint_wrappers=1:nokey=1", path],
                           capture_output=True, text=True, timeout=30)
        return float((r.stdout or "0").strip() or 0)
    except Exception:
        return 0.0


def _decode_window(path: str, start_sec: float, dur_sec: float, sr: int = SR):
    import numpy as np
    fd, tmp = tempfile.mkstemp(suffix=".f32")
    os.close(fd)
    try:
        subprocess.run(["ffmpeg", "-v", "error", "-y", "-ss", f"{start_sec:.2f}",
                        "-t", f"{dur_sec:.2f}", "-i", path,
                        "-map", "0:a:0", "-ac", "1", "-ar", str(sr), "-f", "f32le", tmp],
                       check=True, timeout=120)
        pcm = np.fromfile(tmp, dtype=np.float32)
        return pcm
    finally:
        try:
            os.unlink(tmp)
        except Exception:
            pass


def _spectrum(pcm, sr: int = SR) -> tuple:
    import numpy as np
    n = (len(pcm) // 4096) * 4096
    if n < 4096:
        return 0.0, 0.0, 0
    w = pcm[:n].reshape(-1, 4096).astype(np.float64) * np.hanning(4096)
    mag = np.abs(np.fft.rfft(w, axis=1)).mean(axis=0)
    freqs = np.fft.rfftfreq(4096, 1.0 / sr)
    power = mag ** 2 + 1e-18
    centroid = float((freqs * power).sum() / power.sum())
    hf = float(power[freqs > 6000].sum() / power.sum())
    return centroid, hf, n


def _window_metrics(pcm) -> dict:
    import numpy as np
    if pcm.size == 0:
        return {"rms_db": -120.0, "peak": 0.0, "clips": 0, "click": 0.0,
                "centroid": 0.0, "hf_ratio": 0.0}
    rms = float(np.sqrt((pcm.astype(np.float64) ** 2).mean()))
    peak = float(np.abs(pcm).max())
    diff = np.abs(np.diff(pcm.astype(np.float64)))
    return {
        "rms_db": 20 * np.log10(rms + 1e-12),
        "peak": peak,
        "clips": int((np.abs(pcm) > 0.99).sum()),
        "click": float(diff.max()) if diff.size else 0.0,
        "centroid": _spectrum(pcm)[0],
        "hf_ratio": _spectrum(pcm)[1],
    }


def _stream_profile(path: str) -> str:
    try:
        r = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "a:0",
                            "-show_entries", "stream=profile",
                            "-of", "default=noprint_wrappers=1:nokey=1", path],
                           capture_output=True, text=True, timeout=30)
        return (r.stdout or "").strip()
    except Exception:
        return ""


def _stream_bitrate(path: str) -> float:
    try:
        r = subprocess.run(["ffprobe", "-v", "error", "-select_streams", "a:0",
                            "-show_entries", "stream=bit_rate",
                            "-of", "default=noprint_wrappers=1:nokey=1", path],
                           capture_output=True, text=True, timeout=30)
        return float((r.stdout or "0").strip() or 0)
    except Exception:
        return 0.0


def _structural_check(src: str, dst: str, pct: int, src_dur: float, dst_dur: float) -> dict:
    """Container-level QA for xHE-AAC outputs.

    No CLI decoder on this system (ffmpeg: 'Not yet implemented'; faad 2.10.1:
    MP4 USAC parse failure) can decode USAC/xHE-AAC to PCM, so a spectral
    compare is impossible. The encoder input WAV is generated by us, so content
    integrity is by construction; here we verify duration, container validity,
    and sane bitrate/size instead of failing spuriously on undecodability.
    """
    try:
        size = os.path.getsize(dst)
    except OSError:
        size = 0
    br = _stream_bitrate(dst)
    metrics = {"windows": 0, "src_dur": round(src_dur, 1), "dst_dur": round(dst_dur, 1),
               "dst_bitrate": int(br), "dst_bytes": size}
    if size <= 1024:
        return {"status": "FAIL", "pct": pct, "metrics": metrics, "reason": "xHE-AAC output trivially small"}
    # Floor is deliberately catastrophic-only (~2k): parametric xHE legitimately
    # averages far below nominal on simple content (6s sine -> ~3.5k), so a
    # tight band around target would false-alarm. Near-silence/truncation is
    # still caught here; duration mismatch and trivial size are checked above.
    if br and not 2000 <= br <= 320000:
        return {"status": "WARN", "pct": pct, "metrics": metrics,
                "reason": f"xHE-AAC structural QA only; odd bitrate {br:.0f} — listen before keeping"}
    return {"status": "PASS", "pct": pct, "metrics": metrics,
            "reason": "xHE-AAC structural QA only (duration/container/bitrate OK; "
                      "spectral compare needs an xHE decoder)"}


def quick_check(src: str, dst: str, pct: int = 5, backend: str = "cpu", gpu: int = 0) -> dict:
    """Sampled src-vs-dst QA. backend/gpu accepted for API stability (CPU FFT for now)."""
    import numpy as np
    pct = max(1, min(100, int(pct)))
    if not os.path.exists(dst):
        return {"status": "FAIL", "pct": pct, "reason": "output file missing"}
    if not shutil.which("ffmpeg"):
        return {"status": "WARN", "pct": pct, "reason": "ffmpeg not found, QA skipped"}

    src_dur = _duration(src) or _duration(dst)
    dst_dur = _duration(dst)
    if src_dur > 1 and dst_dur > 1 and abs(src_dur - dst_dur) > max(2.0, src_dur * 0.01):
        return {"status": "FAIL", "pct": pct, "reason": f"duration mismatch src={src_dur:.1f}s dst={dst_dur:.1f}s",
                "metrics": {"src_dur": src_dur, "dst_dur": dst_dur}}

    if _stream_profile(dst) == "xHE-AAC":
        return _structural_check(src, dst, pct, src_dur, dst_dur)

    base = src_dur if src_dur > 1 else 60.0
    win = max(MIN_WIN, min(MAX_WIN, base * pct / 100.0 / len(FRACTIONS)))
    level_deltas, centroid_shifts, hf_deltas = [], [], []
    clicks_added, clips_added, silent_wins, wins = 0, 0, 0, 0
    for frac in FRACTIONS:
        start = max(0.0, base * frac - win / 2)
        try:
            a = _decode_window(src, start, win)
            b = _decode_window(dst, start, win)
        except Exception as e:
            return {"status": "WARN", "pct": pct, "reason": f"decode failed in QA window: {e}"}
        if a.size < 4096 or b.size < 4096:
            continue
        ma, mb = _window_metrics(a), _window_metrics(b)
        wins += 1
        if mb["rms_db"] < -60 and ma["rms_db"] > -50:
            silent_wins += 1
        level_deltas.append(mb["rms_db"] - ma["rms_db"])
        if ma["centroid"] > 100:
            centroid_shifts.append((mb["centroid"] - ma["centroid"]) / ma["centroid"] * 100.0)
        if ma["hf_ratio"] > 1e-6 and mb["hf_ratio"] > 0:
            hf_deltas.append(10 * np.log10(mb["hf_ratio"] / ma["hf_ratio"]))
        if mb["click"] > max(0.6, 3.0 * ma["click"]):
            clicks_added += 1
        if mb["clips"] > ma["clips"]:
            clips_added += mb["clips"] - ma["clips"]

    if wins == 0:
        return {"status": "WARN", "pct": pct, "reason": "no QA windows decoded"}
    metrics = {
        "windows": wins,
        "win_sec": round(win, 1),
        "level_delta_db": round(float(np.mean(level_deltas)), 2),
        "centroid_shift_pct": round(float(np.mean(centroid_shifts)) if centroid_shifts else 0.0, 2),
        "hf_delta_db": round(float(np.mean(hf_deltas)) if hf_deltas else 0.0, 2),
        "click_windows": clicks_added,
        "clips_added": clips_added,
        "silent_windows": silent_wins,
    }
    if silent_wins >= 2 or abs(metrics["level_delta_db"]) > 20:
        return {"status": "FAIL", "pct": pct, "metrics": metrics, "reason": "output silent/collapsed vs source"}
    if abs(metrics["centroid_shift_pct"]) > 25 or metrics["hf_delta_db"] > 6:
        return {"status": "FAIL", "pct": pct, "metrics": metrics,
                "reason": "severe tinny shift / hiss vs source"}
    if (abs(metrics["centroid_shift_pct"]) > 8 or metrics["hf_delta_db"] > 3
            or clicks_added > 0 or clips_added > 0):
        return {"status": "WARN", "pct": pct, "metrics": metrics,
                "reason": "possible tinny/hiss/clicks — listen to flagged windows before keeping"}
    return {"status": "PASS", "pct": pct, "metrics": metrics, "reason": "sampled windows match source"}


def validate_pair(src: str, dst: str, pct: int = 5, backend: str = "cpu", gpu: int = 0) -> dict:
    """Compat wrapper — now backed by the real sampled check."""
    return quick_check(src, dst, pct=pct, backend=backend, gpu=gpu)
